// ----------------------------------------------------------------------------------------------------
// Version number. Will increment when new material flags are added.
// 
// Until the community can decide on a unified PBR specification, 
// third-party pipelines are encouraged to use this for maximum compatibility.
// 
// Gate usage of material flags using #if FMN_PBR >= <required_version>.
// ----------------------------------------------------------------------------------------------------
#define FMN_PBR 5

// ----------------------------------------------------------------------------------------------------
// Flag for whether this material is water and should have water fog and other water-specific effects.
// 
// Water fog color will depend on the water albedo as of FMN_PBR version 2, 
// so set the albedo of the material to whatever you want the water fog color to be.
// 
// Version 1 feature.
// ----------------------------------------------------------------------------------------------------
int fmn_isWater = 0;

// ----------------------------------------------------------------------------------------------------
// Amount of subsurface scattering (SSS) to apply for this material. 
// 
// In FMN, this is implemented such that SSS materials have both shadowmap-based SSS and screenspace SSS.
// Other pipelines may implement fmn_sssAmount in their own way.
// Defaults to 1.0 when diffuse shading is disabled.
// 
// Version 1 feature.
// ----------------------------------------------------------------------------------------------------
float fmn_sssAmount = 0.0;

// ----------------------------------------------------------------------------------------------------
// Flag for whether this material is a player. 
//
// In FMN, this is used to get a depth image without including the player,
// for raytraced handheld light occlusion.
//
// Version 2 feature.
// ----------------------------------------------------------------------------------------------------
int fmn_isPlayer = 0;

// ----------------------------------------------------------------------------------------------------
// Flag for whether this material is foliage.
//
// In FMN, this is used for seasonal foliage tinting.
//
// Version 3 feature.
// ----------------------------------------------------------------------------------------------------
int fmn_isFoliage = 0;

// ----------------------------------------------------------------------------------------------------
// Flag for whether this material is foliage AND a leaf block. 
//
// The effect of this is simply tinting to a different color per season.
// For example, autumn leaves will be orange but other foliage will be a different color.
//
// Version 3 feature.
// ----------------------------------------------------------------------------------------------------
int fmn_isLeafBlock = 0;

// ----------------------------------------------------------------------------------------------------
// Strength of autogenerated normals. Zero disables. 
// 
// Material shaders should use this to avoid complex logic, 
// because that can cause a performance impact due to branching.
// 
// Version 4 feature. As of version 5, this defaults to 1.0.
// ----------------------------------------------------------------------------------------------------
float fmn_autoGenNormalStrength = 1.0;